### PR TITLE
Added support for SH1106 (I2C Wire)

### PR DESCRIPTION
**Pull request by hallard**

### CODE REVIEW

**Comment by FWeinb** [comment]
Thanks for starting this PR. With the 3.0.0 release we splitted the hardware layer from the core library. In its current form this PR is breaking this separation. Please have a look at the other implementations for the ssd1306 and implement the support like that.

**Comment by hallard** [comment]
Sure but my main concern is the init is different and it's located on file oleddisplay.cpp so I can't know from which driver (ssd or sh) I should init the Oled ?

**Comment by squix78** [comment]
I realized that looking at your code. The SH1106 is like a dimension orthogonal to he abstractions we had so far. The previous abstraction separated transmission protocol from high level commands. Now we would need another abstraction for the high level commands. Not quite sure how we can solve that cleanly... @FWeinb : I see two options: a) we integrate the pull request now and clean up in a next major release or b) we wait with integration and see if there is a smooth way to integrate it without major API change.
I think one problem is that Fabrice will be busy with exams these days and I am simply no good C programmer:-) @hallard I hope you will forgive us if we first consider the options before integrating your PR. Either way, it will be a great fundation for any kind of solution...

**Comment by hallard** [comment]
Daniel,
No pb at all, I was not satisfied with my PR but I priviligied the option "something Working" over something clean even if it's far from my favorite way to work ;)

**Comment by FWeinb** [comment]
I just got my display today. I got the display working with minimal changes. I would like @hallard to test the `add-sh1106-support` branch of this repository. You can just replace `#include <SSD1306.h>` with `#include <SH1106.h>` and replace the constructor `SSD1306` with `SH1106`. 
I didn't need to change the initialization code, only the `display` method needed some refinements.

**Comment by hallard** [comment]
@FWeinb 
Just tested, does works like a charm, great job, thanks!

**Comment by FWeinb** [comment]
Thanks for testing @hallard. I added a new PR to add support for displays using this controller. Thanks for the effort you put into this!

**Pull request closed without merging**
