### PR TITLE
Improve text rendering performance

### PR DESCRIPTION
**Pull request by FWeinb**
This PR will change the font definitions to improve the rendering performance described in #9. I included some other minor improvements to performance. 
Because this library is following semver this PR must be released in another major version bumping bringing this library to 3.0.0.

### CODE REVIEW

**Comment by squix78** [comment]
I'm not sure if we should do yet another major release. Do you think this is API breaking because of the fonts?

**Comment by FWeinb** [comment]
Yes. If someone is using the old API definition with this library it won't work.

**Comment by squix78** [comment]
Hi Fabrice. Sorry for not having merged your pull requests into my repository. I was afraid of confusing the users even more than already. It seems sometimes users don't see updates in their Arduino IDE. I opened a 3.0.0 branch for your changes. Do you know how I can merge your changes with that branch?

**Comment by FWeinb** [comment]
I have made some more performance and feature improvements, I will do another PR against the 3.0.0 branch.

**Pull request closed without merging**
