### PR TITLE
Added support for SPI version of OLED display

### PR DESCRIPTION
**Pull request by neptune2**
Added code to support SPI version of the OLED display:
SPIVersion

Users can now select I2C (default) or SPI  in their .ino code.

To make the https://github.com/squix78/esp8266-weather-station code work, see the changes in SSD1306Demo.ino
**or**
simply make the following changes to WeatherStationDemo.ino or WorldClockDemo.ino:

`#include <SPI.h>` 

```
// Pin definitions for SPI
#define OLED_RESET  D0  // RESET
#define OLED_DC     D2  // Data/Command
#define OLED_CS     D8  // Chip select

// Uncomment one of the following based on OLED type
SSD1306 display(true, OLED_RESET, OLED_DC, OLED_CS); // FOR SPI
// SSD1306 display(I2C_DISPLAY_ADDRESS, SDA_PIN, SDC_PIN);
```

### CODE REVIEW

**Comment by neptune2** [comment]
Hi Daniel,
      
      Many thanks for your library and merges - much appreciated.
      
      Regards,
      Andrew
      
      On 4/9/2016 1:56 PM, squix78 wrote:
    
    
      Merged #26.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by squix78** [comment]
I am the one who has to say thanks! Sorry for the long delay, I'm busy with other stuff these days...

**Comment by squix78** [comment]
Hi Andrew (@neptune2) 
Together with Fabrice I'm preparing the next version of the library. @FWeinb  did some great improvements on the development branch but unfortunately those changes made it quite hard to merge your SPI addition to the dev branch. I think I could manage but then wouldn't be able to test them. Would you mind updating your pull request also to the dev branch? That would be awesome!
Regards,
Daniel

**Comment by neptune2** [comment]
Hi Daniel,
      
      I would be glad to.
      
      Regards,
      Andrew
      
      On 5/25/2016 3:44 PM, squix78 wrote:
    
    
      Hi Andrew (@neptune2)
        
        Together with Fabrice I'm preparing the next version of the
        library. @FWeinb
        did some great improvements on the development branch but
        unfortunately those changes made it quite hard to merge your SPI
        addition to the dev branch. I think I could manage but then
        wouldn't be able to test them. Would you mind updating your pull
        request also to the dev branch? That would be awesome!
        Regards,
        Daniel
      —
        You are receiving this because you were mentioned.
        Reply to this email directly or view
          it on GitHub

**Comment by neptune2** [comment]
Hi Daniel (@squix78),

Thanks to Fabrice's (@FWeinb) changes and merge #41 this is no longer needed.

Regards,
Andrew

**Comment by squix78** [comment]
Hi Andrew

Yes, thanks a lot. Fabrice and I decided that another abstraction for hardware support was desperately needed and then Fabrice quickly made it happen. Did/could you test the SPI implementation?

Regards,
Daniel

**Comment by neptune2** [comment]
Thanks @FWeinb for the quick action.

I have confirmed that all demos work correctly on both an I2C and an SPI version of the SSD1306 using a Wemos D1 mini esp8266 board. However I had to make changes to compile on arduino IDE 1.6.5 (r5) to prevent compile errors. I'm not sure if this is fixed in later Arduino releases.

The 1.6.5 changes required are:
- move the `#include "images.h"` to after the display library includes.
- add `#include <SPI.h>` in the .ino demo file directly before `#include "SSD1306Spi.h"` if you are using the SPI display.

Also there is a minor typo in each of the Demo files for the SPI comments:

`// D5 -> SCL`
`// D7 -> SDA`

should be

`// D5 -> CLK`
`// D7 -> MOSI (DOUT)`

Regards,
Andrew

**Comment by neptune2** [comment]
@FWeinb Confirmed that Arduino IDE 1.6.9 and PlatformIO IDE 1.2.2 work correctly without the 1.6.5 changes above.

**Comment by FWeinb** [comment]
Thank you. I will make the changes you mentioned. Glad you tested it with Arduino IDE I am only using PlatformIO these days.

**Comment by FWeinb** [comment]
@neptune2 would be great if you could test it again.

**Comment by neptune2** [comment]
@FWeinb I have confirmed all demos work as expected _without_ code changes (except commenting/uncommenting required code). I specifically checked both Arduino 1.6.5 and 1.6.9 (using esp8266 2.2.0) and PlatformIO IDE 1.2.2 using both I2C and SPI displays with Wire I2C, brzo I2C and SPI libraries (as appropriate).

I found some recommended pairings. Just as `#include <SPI.h>` is only needed with `#include "SSD1306Spi.h"` in Arduino 1.6.5 (and earlier?), so also, `#include <Wire.h>` is only needed with `#include "SSD1306.h"`. I also had to add `#include <brzo_i2c.h>` when using `#include "SSD1306Brzo.h"` with Arduino 1.6.5.

The following is the recommended code:

```
// Include the correct display library
// For a connection via I2C using Wire include
#include <Wire.h>  // Only needed for Arduino 1.6.5 and earlier
#include "SSD1306.h" // alias for `#include "SSD1306Wire.h"`
// For a connection via I2C using brzo_i2c (must be installed) include
// #include <brzo_i2c.h> // Only needed for Arduino 1.6.5 and earlier
// #include "SSD1306Brzo.h"
// For a connection via SPI include
// #include <SPI.h> // Only needed for Arduino 1.6.5 and earlier
// #include "SSD1306Spi.h"
```

One other suggested change for clarification:
I would recommend changing
`// Initialize the OLED display using Wire library`
to
`// Initialize the OLED display using I2C Wire library`

Side-by-side SSD1306ClockDemo on I2C (left) vs SPI (right) displays
being driven by Wemos D1R2 and D1  mini
img_1003s

**Comment by FWeinb** [comment]
Awesome thank you for these extensive tests! Will fix the remaining issues.

**Pull request merged**
